<?php

use Illuminate\Database\Migrations\Migration;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Support\Facades\Schema;

return new class extends Migration
{
    /**
     * Run the migrations.
     */
    public function up(): void
    {
        Schema::create('payouts', function (Blueprint $table) {
            $table->id();      
            $table->foreignId('user_id')->constrained('users')->onDelete('cascade');
            $table->foreignId('batch_id')->nullable()->constrained('batch_payouts')->onDelete('cascade');

            // unique transaction id for each payout request, generated by the system
            $table->string('merchant_reference_id')->nullable()->unique();
            $table->string('transaction_id')->unique();
            $table->string('sprintnxt_txn_id')->nullable();
            $table->tinyInteger('txn_status')->nullable();
            $table->string('sprintnxt_logger_id')->nullable();


            // UTR (Unique Transaction Reference) provided by the bank/payment gateway for each transaction, can be null for pending transactions
            $table->string('utr')->nullable();

            // Date time when the payout request was initiated
            $table->timestamp('initiated_at')->useCurrent();

            // Date time when the payout request was processed (success or failure)
            $table->timestamp('processed_at')->nullable();

            // payee details            
            $table->string('account_holder', 255);
            $table->string('account_number');
            $table->string('ifsc_code');
            $table->string('branch_code');
            $table->string('bank_name');
            $table->string('branch_name'); // e.g. Karol Bagh, New Delhi
            $table->string('mobile');
            $table->string('email')->nullable();
            $table->string('city');
            $table->string('state')->nullable();
            $table->string('pincode')->nullable();

            // beneficiary details
            $table->string('beneficiary_address', 255); // e.g. delhi

            // payout details
            $table->decimal('amount', 16, 2);
            $table->decimal('fee', 16, 2)->default(0);
            $table->decimal('total_amount', 16, 2)->default(0); // amount + fee

            // opening and closing balance for the VAN
            $table->decimal('opening_balance', 16, 2)->default(0);
            $table->decimal('closing_balance', 16, 2)->default(0);


            $table->string('mode'); //Transaction mode. ( imps,neft,rtgs,a2a)
            $table->enum('status', ['initiated', 'success', 'pending', 'failed', 'processed', 'send_to_bank'])->default('initiated');

            $table->text('remarks')->nullable();
            $table->text('purpose')->nullable();
            $table->text('narration')->nullable();

            // store the complete response from the payment gateway for future reference and debugging
            $table->json('raw_payload')->nullable();

            // hit by api or portal
            $table->string('initiated_from', 255)->default('api');

            $table->timestamps();
        });
    }

    /**
     * Reverse the migrations.
     */
    public function down(): void
    {
        Schema::dropIfExists('payouts');
    }
};
