<?php

use Illuminate\Database\Migrations\Migration;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Support\Facades\Schema;

return new class extends Migration
{
    /**
     * Run the migrations.
     */
    public function up(): void
    {
        Schema::create('batch_payouts', function (Blueprint $table) {
            $table->id();
            $table->foreignId('user_id')->constrained()->onDelete('cascade');
            $table->string('batch_id')->unique();
            $table->string('system_batch_id')->unique()->nullable()->comment('Batch ID generated by the system for internal tracking');

            $table->integer('batch_count')->comment('Number of payouts in the batch');
            $table->decimal('batch_amount', 15, 2)->comment('Total amount');

            $table->integer('accepted_count')->default(0)->comment('Number of accepted payouts');
            $table->integer('rejected_count')->default(0)->comment('Number of rejected payouts');

            $table->string('tracker_id')->nullable()->comment('Unique identifier for tracking the batch across systems');

            $table->timestamps();
        });
    }

    /**
     * Reverse the migrations.
     */
    public function down(): void
    {
        Schema::dropIfExists('batch_payouts');
    }
};
